### PR TITLE
JCL syntax hiliter update

### PR DESCRIPTION
**Pull request by Martin-Zeithaml**
Signed-off-by: Martin Zeithaml <Martin.Zeithaml@broadcom.com>

## Proposed changes
Small update to JCL hiliter.

This PR addresses Issue: [#839](https://github.com/zowe/zlux/issues/839)

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

## PR Checklist
Please delete options that are not relevant.
- [x] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zlux/blob/master/CONTRIBUTING.md))
- [x] I have commented my code, particularly in hard-to-understand areas

## Testing

Manual testing:
- JCL syntax by comparing editor with and without fix
- Debug messages in developer's console are shown only when production is set to false

### CODE REVIEW

**Comment by Martin-Zeithaml** [comment]
When this PR will be merged, I will do the same for v2.x. It is possible, that during the testing more changes will be done.

**Review by DivergentEuropeans — APPROVED** [review]
This is an excellent change, and I manually compared this, what we have, and what ISPF has, and for all of my files tested, this is better highlighting - thank you very much! @Martin-Zeithaml
A huge improvement

**Comment by Martin-Zeithaml** [comment]
I have updated the CHANGELOG and also setting of ```jclDebug``` variable.

**Review by DivergentEuropeans — COMMENTED** [review]
@struga0258 was kind enough to test, merging. Thank you 👍 @Martin-Zeithaml

**Pull request merged**
