### PR TITLE
selecting first tab on close of selected tab

### PR DESCRIPTION
**Pull request by NakulManchanda**
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>

### CODE REVIEW

**Comment by NakulManchanda** [comment]
@1000TurquoisePogs can you make yourself reviewer

we can still improve to open a adjacent tab, for now i am selecting first tab
this is to resolve 
https://github.com/1000TurquoisePogs/zlux-editor/blob/c821f34756fb264d8bbb2f9344d1ad9e2c5ba810/webClient/src/app/editor/code-editor/code-editor.component.ts#L93

**Comment by NakulManchanda** [comment]
There are two ways to close files - 
1) double click 
2) and use "x" close icon on tab
only one of them was calling `closeFile` function on closing file
added new close file subscribe in code-editor component - as that called by both and step to select if none selected out of open file

**Comment by jordanCain** [comment]
resolves https://github.com/zowe/zlux/issues/135

**Comment by DivergentEuropeans** [comment]
Hey @NakulManchanda,

Thanks for the contribution. I will take a look and review over the weekend, and get back to @1000TurquoisePogs so he can merge. He is away for a few days and will be back on Tuesday.

**Comment by 1000TurquoisePogs** [comment]
Thanks, looks good!

**Comment by NolanRogers** [comment]
Can this be closed?

**Pull request merged**
